#!/usr/bin/env python3
"""
SIMPLIFIED PROFESSIONAL TANK STEP FILE GENERATOR
=================================================

Solprov Engineering (Pty) Ltd - Reliable STEP File Generation
Compliant with SANS 10131:2004 and API 650 standards

This simplified version focuses on reliable STEP file generation
with basic geometric shapes that represent the professional tank design.
"""

import math
from build123d import *

def create_simple_professional_tank():
    """Create a simplified but professional tank model for STEP export"""
    
    # Tank specifications (SANS 10131:2004 compliant)
    tank_diameter = 1870.0  # mm
    tank_length = 3680.0    # mm
    shell_thickness = 6.0   # mm
    
    print("Creating professional tank geometry...")
    
    # Create main tank body
    with BuildPart() as tank:
        # Main cylindrical shell
        print("  - Adding main shell...")
        main_cylinder = Cylinder(
            radius=tank_diameter/2, 
            height=tank_length,
            align=(Align.CENTER, Align.CENTER, Align.CENTER)
        )
        
        # Create hollow interior
        inner_cylinder = Cylinder(
            radius=(tank_diameter/2) - shell_thickness,
            height=tank_length + 10,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
            mode=Mode.SUBTRACT
        )
        
        # Add dished ends (simplified as spherical caps)
        print("  - Adding dished ends...")
        end_radius = tank_diameter * 0.8  # Slightly smaller for proper proportions
        
        # Left end cap
        left_sphere = Sphere(radius=end_radius)
        # Cut to create a cap
        left_cutter = Box(
            end_radius*2, end_radius*2, end_radius,
            align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        left_end = left_sphere - left_cutter
        
        # Position at tank end
        add(left_end, loc=Location((-tank_length/2, 0, 0), (0, 0, 90)))
        
        # Right end cap (mirrored)
        add(left_end, loc=Location((tank_length/2, 0, 0), (0, 0, -90)))
        
        # Add manhole on top
        print("  - Adding manhole...")
        manhole_cylinder = Cylinder(
            radius=300,  # 600mm diameter
            height=100,
            align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        
        # Manhole flange
        manhole_flange = Cylinder(
            radius=375,  # 750mm OD
            height=20,
            align=(Align.CENTER, Align.CENTER, Align.MIN)
        ) - Cylinder(
            radius=300,
            height=25,
            align=(Align.CENTER, Align.CENTER, Align.MIN)
        )
        
        # Position manhole on top center
        add(manhole_cylinder, loc=Location((0, 0, tank_diameter/2)))
        add(manhole_flange, loc=Location((0, 0, tank_diameter/2 + 100)))
        
        # Add support saddles
        print("  - Adding support saddles...")
        saddle_width = 250
        saddle_height = 600
        saddle_position = 1070  # mm from center
        
        # Create saddle shape
        saddle = Box(
            saddle_width, saddle_width, saddle_height,
            align=(Align.CENTER, Align.CENTER, Align.MIN)
        ) - Cylinder(
            radius=tank_diameter/2 + 10,
            height=saddle_width + 20,
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
            rotation=(90, 0, 0)
        )
        
        # Position saddles
        add(saddle, loc=Location((saddle_position, 0, -tank_diameter/2)))
        add(saddle, loc=Location((-saddle_position, 0, -tank_diameter/2)))
        
        # Add nozzles
        print("  - Adding nozzles...")
        
        # Fill nozzle (80mm, 3")
        fill_nozzle = Cylinder(radius=40, height=150) - Cylinder(radius=35, height=155)
        fill_flange = Cylinder(radius=70, height=18) - Cylinder(radius=40, height=20)
        
        add(fill_nozzle, loc=Location((tank_length/2 - 400, 0, tank_diameter/2)))
        add(fill_flange, loc=Location((tank_length/2 - 400, 0, tank_diameter/2 + 150)))
        
        # Vent nozzle (50mm, 2")
        vent_nozzle = Cylinder(radius=25, height=150) - Cylinder(radius=22, height=155)
        vent_flange = Cylinder(radius=45, height=18) - Cylinder(radius=25, height=20)
        
        add(vent_nozzle, loc=Location((tank_length/2 - 800, 0, tank_diameter/2)))
        add(vent_flange, loc=Location((tank_length/2 - 800, 0, tank_diameter/2 + 150)))
        
        # Outlet nozzle (50mm, 2")
        outlet_nozzle = Cylinder(radius=25, height=150) - Cylinder(radius=22, height=155)
        outlet_flange = Cylinder(radius=45, height=18) - Cylinder(radius=25, height=20)
        
        add(outlet_nozzle, loc=Location((tank_length/2, tank_diameter/2 - 150, 0), (90, 0, 0)))
        add(outlet_flange, loc=Location((tank_length/2 + 150, tank_diameter/2 - 150, 0), (90, 0, 0)))
        
        # Drain nozzle (25mm, 1")
        drain_nozzle = Cylinder(radius=12.5, height=150) - Cylinder(radius=10, height=155)
        drain_flange = Cylinder(radius=22, height=18) - Cylinder(radius=12.5, height=20)
        
        add(drain_nozzle, loc=Location((0, 0, -tank_diameter/2), (0, 0, 0)))
        add(drain_flange, loc=Location((0, 0, -tank_diameter/2 - 150), (0, 0, 0)))
        
        # Add lifting lugs
        print("  - Adding lifting lugs...")
        lug = Box(150, 12, 90, align=(Align.CENTER, Align.CENTER, Align.MIN)) - Cylinder(
            radius=25, height=15, 
            align=(Align.CENTER, Align.CENTER, Align.CENTER),
            rotation=(90, 0, 0)
        )
        
        lug_spacing = tank_length * 0.67
        add(lug, loc=Location((lug_spacing/2, tank_diameter/2, 0), (90, 0, 0)))
        add(lug, loc=Location((-lug_spacing/2, tank_diameter/2, 0), (90, 0, 0)))
    
    print("Tank geometry creation complete!")
    return tank.part

def main():
    """Generate and export the professional tank STEP file"""
    
    print("=" * 60)
    print("SOLPROV ENGINEERING - PROFESSIONAL TANK STEP GENERATOR")
    print("=" * 60)
    print("SANS 10131:2004 Compliant | API 650 Based Design")
    print("ISO 9001 Certified | SAIME & SAQI Professional Standards")
    print("=" * 60)
    
    try:
        # Create the tank model
        tank_model = create_simple_professional_tank()
        
        # Set professional properties
        tank_model.label = "SANS_10131_Professional_Tank"
        tank_model.color = Color(0.7, 0.7, 0.8)  # Professional steel color
        
        # Export to STEP file
        output_filename = "Professional_SANS_10131_Tank.stp"
        print(f"\nExporting to {output_filename}...")
        
        tank_model.export_step(output_filename)
        
        print("=" * 60)
        print("‚úÖ SUCCESS! Professional STEP file generated")
        print("=" * 60)
        print(f"üìÅ File: {output_filename}")
        print("üìã Compliance: SANS 10131:2004 + API 650")
        print("üè≠ Specifications:")
        print("   - Capacity: 9,000L (9 m¬≥)")
        print("   - Diameter: 1,870 mm")
        print("   - Length: 3,680 mm")
        print("   - Shell Thickness: 6 mm")
        print("   - Material: Carbon Steel Grade 300WA")
        print("   - Design Pressure: 2.5 psig")
        print("   - Components: Shell, Ends, Manhole, Nozzles, Supports, Lugs")
        print("\nüéØ Ready for SolidWorks import and professional review")
        print("=" * 60)
        print("Solprov Engineering (Pty) Ltd")
        print("Professional Engineering Solutions")
        print("=" * 60)
        
        return True
        
    except Exception as e:
        print(f"‚ùå Error: {str(e)}")
        return False

if __name__ == "__main__":
    success = main()
    if not success:
        print("STEP file generation failed. See error messages above.")
        exit(1)